DROP TABLE if exists geologicalclasses;
DROP TABLE if exists sections;

CREATE TABLE sections
(
    name VARCHAR(255) NOT NULL PRIMARY KEY
);

CREATE TABLE geologicalclasses
(
    id          INTEGER      NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    code        VARCHAR(255) NOT NULL,
    geo_section VARCHAR(255) REFERENCES sections (name)

);