package ru.paracells.natlex.service;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import ru.paracells.natlex.models.GeologicalClass;
import ru.paracells.natlex.models.Section;

import java.util.concurrent.ThreadLocalRandom;

@Service
public class UtilsServiceImpl implements UtilsService {


    @Value("${generate.geo_class}")
    private int NUMBER_OF_GEO_CLASS; // generated by random


    public void addToList(Section section, int value) {
        ThreadLocalRandom random = ThreadLocalRandom.current();
        for (int i = 1; i <= random.nextInt(1, NUMBER_OF_GEO_CLASS + 1); i++) {
            GeologicalClass geologicalClass = new GeologicalClass();
            geologicalClass.setName("Geo Class " + value + i);
            geologicalClass.setCode("GC" + value + i);
            section.getGeoClasses().add(geologicalClass);
            section.getGeoClasses().add(geologicalClass);
        }
    }
}
